version: "2"
networks:
  elk:
    external: true
services:
  dating:
    restart: on-failure
    image: registry.ru/project:tag
    user: "33:33"
    ports:
    - 8009:8000
    extends:
      file: base.yml
      service: base
    networks:
    - elk
    links:
    - redis
    depends_on:
    - redis
    volumes:
    - /var/www/project/static/:/usr/src/app/static/
    command: ["uwsgi", "--http", ":8000", "--processes", "25", "--threads", "4", "--wsgi-file", "config/wsgi.py"]
  redis:
    image: "redis:alpine"
    networks:
    - elk
  celery:
    image: registry.ru/project:tag
    user: "33:33"
    ports: []
    extends:
      file: base.yml
      service: base
    networks:
    - elk
    links:
    - redis
    depends_on:
    - redis
    - volumes:
    - /var/www/project/static/:/usr/src/app/static/
    command: ["celery", "worker", "-A", "config", "--loglevel=debug"]
  celery_beat:
    image: registry.ru/project:tag
    user: "33:33"
    ports: []
    extends:
      file: base.yml
      service: base
    networks:
    - elk
    links:
    - redis
    depends_on:
    - redis
    volumes:
    - /var/www/project/static/:/usr/src/app/static/
    command: ["celery", "beat", "-A", "config", "--loglevel=debug", "--scheduler", "django_celery_beat.schedulers:DatabaseScheduler", "--pidfile="]
  celery_flower:
    image: registry.ru/project:tag
    user: "33:33"
    ports:
    - 5555:5555
    extends:
      file: base.yml
      service: base
    networks:
     - elk
    links:
    - redis
    depends_on:
    - redis
    volumes:
    - /var/www/project/static/:/usr/src/app/static/
    command: ["flower", "-A", "config", "--port=5555"]

